In [3]:
import pandas as pd
import os
import shutil
import os.path
import numpy as np

In [4]:
df = pd.read_csv("facial_expressions/data/legend.csv")
del df['Unnamed: 0']
del df['user.id']
df.head()

                             image   emotion
0  facial-expressions_2868588k.jpg     anger
1  facial-expressions_2868585k.jpg  surprise
2  facial-expressions_2868584k.jpg   disgust
3  facial-expressions_2868582k.jpg      fear
4           Aaron_Eckhart_0001.jpg   neutral

In [5]:
len(df)

13690

In [6]:
unique_emotions = list(df['emotion'].unique())
unique_emotions

['anger',
 'surprise',
 'disgust',
 'fear',
 'neutral',
 'happiness',
 'sadness',
 'contempt']

In [7]:
df = df.sample(frac = 1) 
train = df[0:int(len(df['image'])*0.6)]
valid = df[int(len(df['image'])*0.6):]
train = train.reset_index()
valid = valid.reset_index()

In [8]:
!mkdir train
!mkdir valid

In [10]:
for index in train.index:
    if (index % 100 == 0):
        print(index)
    source = "./facial_expressions/images/"+train['image'][index]
    destination = './train/'+train['emotion'][index]+'/'+train['image'][index]
    if (os.path.exists(source) and not (os.path.exists(destination))):
        try:
            dest = shutil.move(source, destination)
        except:
            os.mkdir('train/'+train['emotion'][index])
            dest = shutil.move(source,destination)

0
100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700
5800
5900
6000
6100
6200
6300
6400
6500
6600
6700
6800
6900
7000
7100
7200
7300
7400
7500
7600
7700
7800
7900
8000
8100
8200

In [11]:
for index in valid.index:
    if (index % 100 == 0):
        print(index)
    source = "./facial_expressions/images/"+valid['image'][index]
    destination = './valid/'+valid['emotion'][index]+'/'+valid['image'][index]
    
    if (os.path.exists(source) and not (os.path.exists(destination))):
        try:
            dest = shutil.move(source, destination)
        except:
            os.mkdir('valid/'+valid['emotion'][index])
            dest = shutil.move(source,destination)

0
100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400

In [19]:
os.remove("./output/valid_lst.lst")

In [6]:
file = open('./output/train_lst.lst', 'w+')
emotions = unique_emotions
counter = 0
for index in train.index:
    val_index = unique_emotions.index(train['emotion'][index])
    source = "./train/"+unique_emotions[val_index]+"/"+train['image'][index]
    output_path = './output/'+unique_emotions[val_index]+"/"+train['image'][index]
    
    path_in_file = unique_emotions[val_index]+"/"+train['image'][index]
    
    
    if (os.path.exists(source) and not (os.path.exists(output_path))):
        try:
            dest = shutil.move(source, output_path)
        except:
            os.mkdir('output/'+train['emotion'][index])
            dest = shutil.move(source,output_path)
            
    if (os.path.exists(output_path)):
        file.write('%d\t%d\t%s\n' % (counter, val_index, path_in_file))
        counter += 1

In [7]:
file = open('./output/valid_lst.lst', 'w+')
emotions = unique_emotions
counter = 0
for index in valid.index:
    val_index = unique_emotions.index(valid['emotion'][index])
    source = "./valid/"+unique_emotions[val_index]+"/"+valid['image'][index]
    output_path = './output/'+unique_emotions[val_index]+"/"+valid['image'][index]
    
    path_in_file = unique_emotions[val_index]+"/"+valid['image'][index]
    
    if (os.path.exists(source) and not (os.path.exists(output_path))):
        try:
            dest = shutil.move(source, output_path)
        except:
            os.mkdir('output/'+valid['emotion'][index])
            dest = shutil.move(source,output_path)
    
    if (os.path.exists(output_path)):
        file.write('%d\t%d\t%s\n' % (counter, val_index, path_in_file))
        counter += 1

In [1]:
!mkdir anger
!mkdir surprise
!mkdir disgust
!mkdir fear
!mkdir neutral
!mkdir happiness
!mkdir sadness
!mkdir contempt

In [2]:
!mkdir output

In [29]:
len(df)

13690

In [10]:
train_dict = {'image': [], 'value':[]}
emotions = ['anger', 'surprise', 'disgust', 'fear', 'neutral', 'happiness', 'sadness', 'contempt']
counter = 0
for index in train.index:
    val_index = unique_emotions.index(train['emotion'][index])
    source = "./train/"+unique_emotions[val_index]+"/"+train['image'][index]
    output_path = './output/'+unique_emotions[val_index]+"/"+train['image'][index]
    
    if (os.path.exists(output_path)):
        train_dict['image'].append(output_path)
        train_dict['value'].append(val_index)

train_df = pd.DataFrame(data = train_dict)
train_df

                                              image  value
0           ./output/neutral/George_W_Bush_0020.jpg      4
1     ./output/happiness/Mohamed_ElBaradei_0008.jpg      5
2        ./output/happiness/Candice_Bergen_0003.jpg      5
3         ./output/neutral/Donald_Rumsfeld_0093.jpg      4
4        ./output/neutral/Millicent_Martin_0001.jpg      4
...                                             ...    ...
8208      ./output/neutral/James_McGreevey_0003.jpg      4
8209     ./output/happiness/Angelina_Jolie_0002.jpg      5
8210        ./output/neutral/Marc_Grossman_0002.jpg      4
8211          ./output/neutral/John_Madden_0001.jpg      4
8212         ./output/neutral/Kyle_McLaren_0001.jpg      4

[8213 rows x 2 columns]

In [11]:
val_dict = {'image': [], 'value':[]}
emotions = ['anger', 'surprise', 'disgust', 'fear', 'neutral', 'happiness', 'sadness', 'contempt']
counter = 0
for index in valid.index:
    val_index = unique_emotions.index(valid['emotion'][index])
    source = "./train/"+unique_emotions[val_index]+"/"+valid['image'][index]
    output_path = './output/'+unique_emotions[val_index]+"/"+valid['image'][index]
    
    if (os.path.exists(output_path)):
        val_dict['image'].append(output_path)
        val_dict['value'].append(val_index)

val_df = pd.DataFrame(data = val_dict)
val_df

                                               image  value
0         ./output/happiness/Saddam_Hussein_0016.jpg      5
1     ./output/neutral/Jean-Pierre_Raffarin_0001.jpg      4
2             ./output/neutral/Bob_Guccione_0001.jpg      4
3      ./output/happiness/Princess_Caroline_0004.jpg      5
4             ./output/neutral/Anil_Ramsook_0001.jpg      4
...                                              ...    ...
5471        ./output/neutral/Heizo_Takenaka_0004.jpg      4
5472          ./output/neutral/Erik_Morales_0002.jpg      4
5473          ./output/happiness/Laura_Bush_0023.jpg      5
5474     ./output/happiness/Irina_Yatchenko_0001.jpg      5
5475          ./output/disgust/HrithikRoshan_118.jpg      2

[5476 rows x 2 columns]

In [12]:
train_df.to_csv('train.csv')
val_df.to_csv('val.csv')